from . import mail
from . import interview
from . import partner
from . import applicant
from . import applicant_history
from . import job
from . import offer
from . import res_users
from . import policy
from . import hr_set_daily_target
#test automation build mail