from . import abstract_rec_report_wizard
from . import recrutier_activity_wizard
from . import general_sheet_report_wizard
from . import approval_cycle_wizard
from . import offer_wizard
from . import interview_mail_compose_message
from . import compliance_report_wizard
from . import interview_report_wizard
from . import generate_daily_target_report_wizard
from . import generate_monthly_target_report_wizard
from . import generate_rejection_mail_message
from . import approval_cycle_mail_message_wizard
from . import send_hr_mail_message_wizard