# -*- coding: utf-8 -*-
# noinspection PyStatementEffect
{
    'name': 'Recruitment ADS - Word',
    'version': '2.1.0',
    'summary': 'Recruitment Management',
    'category': 'Employees',
    'author': 'AHBS Odoo Team',
    'website': "http://www.andalusiagroup.net",
    'sequence': 30,
    'description': """
Handle recruitment Process for Andalusia
    """,
    'depends': ['base', 'base_setup', 'bus', 'web_tour', 'hr_recruitment', 'mail', 'sync_ldap_ads', 'report_xlsx',
                'decimal_precision', 'contacts'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/mail_templates.xml',
        'views/interview_view.xml',
        'views/interview_templates.xml',
        'data/call_result_data.xml',
        'data/interview_data.xml',
        'data/interview_email_templates.xml',
        'data/jobs_data.xml',
        'reports/reports.xml',
        'data/offer_data.xml',
        'data/sequence.xml',
        'data/job_mail_template.xml',
        'views/offer_view.xml',
        'views/applicant_view.xml',
        'views/job_view.xml',
        'views/hr_section_view.xml',
        'views/hr_department_view.xml',
        'views/policy.xml',
        'views/res_users_view.xml',
        'views/hr_set_daily_target_view.xml',
        'wizard/recruitment_wizard_view.xml',
        'wizard/offer_wizard_view.xml',
        'wizard/interview_mail_compose_message_wizard_view.xml',
        'wizard/generate_daily_target_report_wizard.xml',
        'wizard/compliance_report_wizard.xml',
        'reports/offer_egypt_template.xml',
        'reports/offer_ksa_template.xml',
    ],

    'qweb': [
        'static/src/xml/activity.xml',
        'static/src/xml/fields.xml',
        'static/src/xml/dialog.xml',
    ],

    'installable': True,
    'application': True,
    'auto_install': False,
}
